language: r
sudo: false
install:
- Rscript -e 'install.packages("devtools", repos = "http://cran.rstudio.com")'
- Rscript -e 'devtools::install_deps("finalProject")'
- R -e "0" --args --bootstrap-packrat
script:
- Rscript -e 'devtools::check("finalProject")'
cache:
  directories: $TRAVIS_BUILD_DIR/packrat/
  packages: true
